image: registry.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build

# Job template for test stage
.test:
<<<<<<< HEAD
  image: nikolaik/python-nodejs:python3.8-nodejs12
=======
  image: node:12.18.3
>>>>>>> 217b562... modification after changing the frame:
  stage: test

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
<<<<<<< HEAD
      - frontend/node_modules/

  before_script:
    - cd frontend/
    - npm config set registry https://registry.npm.taobao.org
    - npm install
    - cd ..
=======
      - node_modules/

  before_script:
    - npm config set registry https://registry.npm.taobao.org
    - npm install
>>>>>>> 217b562... modification after changing the frame:

unit-test:
  extends: .test
  script:
<<<<<<< HEAD
    - cd frontend/
    - npm install axios --save
    - npm install mocha --save
    - npm test
    - FRONTEND_RET=$?
    - if [ $FRONTEND_RET \> 0 ]; then exit $FRONTEND_RET; fi;
    - exit $BACKEND_RET
    - cd ..
  after_script:
    - SUFFIX=$RANDOM
    - curl "http://10.0.0.11/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz" -C .

style-test:
  extends: .test
  allow_failure: true
  script:
    - cd frontend/
    - npm run eslint
    - FRONTEND_RET=$?
    - if [ $FRONTEND_RET \> 0 ]; then exit $FRONTEND_RET; fi;
    - exit $BACKEND_RET
    - cd ..
=======
    - npm test
    - FRONTEND_RET=$?
    - npm run test:backend
    - BACKEND_RET=$?
    - if [ $FRONTEND_RET \> 0 ]; then exit $FRONTEND_RET; fi;
    - exit $BACKEND_RET
  after_script:
    - SUFFIX=$RANDOM
    - curl "http://10.0.0.11/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz"  -C /opt
    - /opt/sonar-scanner/bin/sonar-scanner

style-test:
  extends: .test
  # allow_failure: true
  script:
    - npm run lint
>>>>>>> 217b562... modification after changing the frame:

deploy:
  stage: deploy
  script:
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - master
<<<<<<< HEAD

=======
>>>>>>> 217b562... modification after changing the frame:
